language: node_js

node_js:
  - 0.11

before_script:
  - npm install -g ember-cli
  - npm install -g bower
  - npm install
  - bower -F install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script: BROCCOLI_ENV=test ember test
