language: node_js

node_js:
  - 0.11

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
  - sudo apt-get update;
  - sudo apt-get install gcc-4.8 g++-4.8;
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20;
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20;
  - sudo g++ --version;
  - sudo apt-get update -qq;

before_script:
  - npm install -g bower
  - npm install
  - bower -F install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script: BROCCOLI_ENV=test ./node_modules/broccoli-testem/bin/broccoli-testem
